// FrontEnd/src/components/Login.jsx
import { useState } from 'react';
import { MAJORS_LIST } from '../utils/majors';
import './Login.css';

export default function Login({ onLogin }) {
  const [isRegistering, setIsRegistering] = useState(false);
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    major: '',
    grad_year: new Date().getFullYear() + 1
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const majors = MAJORS_LIST;

  const currentYear = new Date().getFullYear();
  const gradYears = Array.from({ length: 10 }, (_, i) => currentYear + i);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const validateEmail = (email) => {
    const uncPattern = /^[a-zA-Z0-9._%+-]+@(unc\.edu|live\.unc\.edu|ad\.unc\.edu)$/;
    return uncPattern.test(email.toLowerCase());
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    // Validate email
    if (!validateEmail(formData.email)) {
      setError('Please use a valid UNC email address (@unc.edu, @live.unc.edu, or @ad.unc.edu)');
      setLoading(false);
      return;
    }

    try {
      const endpoint = isRegistering ? '/auth/register' : '/auth/login';
      const payload = isRegistering ? formData : { 
        email: formData.email, 
        password: formData.password 
      };

      const response = await fetch(`http://localhost:8000${endpoint}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      });

      const data = await response.json();

      if (response.ok) {
        // Store token and user data
        localStorage.setItem('token', data.access_token);
        localStorage.setItem('user', JSON.stringify(data.user));
        onLogin(data.user);
      } else {
        setError(data.detail || 'Authentication failed');
      }
    } catch (error) {
      console.error('Auth error:', error);
      setError('Network error. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <div className="login-header">
          <h1>StudySync</h1>
          <p className="tagline">UNC Class & Professor Ratings</p>
        </div>

        <div className="auth-toggle">
          <button 
            type="button"
            className={!isRegistering ? 'active' : ''}
            onClick={() => setIsRegistering(false)}
          >
            Sign In
          </button>
          <button 
            type="button"
            className={isRegistering ? 'active' : ''}
            onClick={() => setIsRegistering(true)}
          >
            Sign Up
          </button>
        </div>

        <form onSubmit={handleSubmit} className="auth-form">
          {error && <div className="error-message">{error}</div>}
          
          <div className="form-group">
            <label htmlFor="email">UNC Email</label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              placeholder="yourname@unc.edu"
              required
              disabled={loading}
            />
          </div>

          <div className="form-group">
            <label htmlFor="password">Password</label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              placeholder={isRegistering ? "At least 8 characters with letters and numbers" : "Enter your password"}
              required
              disabled={loading}
              minLength={isRegistering ? 8 : undefined}
            />
          </div>

          {isRegistering && (
            <>
              <div className="form-group">
                <label htmlFor="major">Major</label>
                <select
                  id="major"
                  name="major"
                  value={formData.major}
                  onChange={handleChange}
                  required
                  disabled={loading}
                >
                  <option value="">Select your major</option>
                  {majors.map(major => (
                    <option key={major} value={major}>{major}</option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label htmlFor="grad_year">Graduation Year</label>
                <select
                  id="grad_year"
                  name="grad_year"
                  value={formData.grad_year}
                  onChange={handleChange}
                  required
                  disabled={loading}
                >
                  {gradYears.map(year => (
                    <option key={year} value={year}>{year}</option>
                  ))}
                </select>
              </div>
            </>
          )}

          <button 
            type="submit" 
            className="submit-button"
            disabled={loading}
          >
            {loading ? 'Loading...' : (isRegistering ? 'Create Account' : 'Sign In')}
          </button>
        </form>

        <div className="login-footer">
          <p>
            {isRegistering ? 'Already have an account?' : "Don't have an account?"}{' '}
            <button 
              type="button"
              className="link-button"
              onClick={() => setIsRegistering(!isRegistering)}
            >
              {isRegistering ? 'Sign In' : 'Sign Up'}
            </button>
          </p>
        </div>
      </div>
    </div>
  );
}

// angular-frontend/src/app/components/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { UserCreateRequest, LoginRequest } from '../../models/user.model';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  isRegistering = false;
  loading = false;
  error = '';

  formData = {
    email: '',
    password: '',
    major: '',
    gradYear: new Date().getFullYear() + 1
  };

  majors = [
    'Applied Sciences',
    'Art',
    'Biology',
    'Business Administration',
    'Chemistry',
    'Computer Science',
    'Data Science',
    'Economics',
    'Neuroscience',
    'Physics'
  ];

  get gradYears(): number[] {
    const currentYear = new Date().getFullYear();
    return Array.from({ length: 10 }, (_, i) => currentYear + i);
  }

  validateEmail(email: string): boolean {
    const uncPattern = /^[a-zA-Z0-9._%+-]+@(unc\.edu|live\.unc\.edu|ad\.unc\.edu)$/;
    return uncPattern.test(email.toLowerCase());
  }

  onSubmit(): void {
    this.loading = true;
    this.error = '';

    if (!this.validateEmail(this.formData.email)) {
      this.error = 'Please use a valid UNC email address (@unc.edu, @live.unc.edu, or @ad.unc.edu)';
      this.loading = false;
      return;
    }

    if (this.isRegistering) {
      const request: UserCreateRequest = {
        email: this.formData.email,
        password: this.formData.password,
        major: this.formData.major,
        gradYear: this.formData.gradYear
      };

      this.authService.register(request).subscribe({
        next: () => this.router.navigate(['/majors']),
        error: (err) => {
          this.error = err.error?.detail || 'Registration failed';
          this.loading = false;
        }
      });
    } else {
      const request: LoginRequest = {
        email: this.formData.email,
        password: this.formData.password
      };

      this.authService.login(request).subscribe({
        next: () => this.router.navigate(['/majors']),
        error: (err) => {
          this.error = err.error?.detail || 'Login failed';
          this.loading = false;
        }
      });
    }
  }

  toggleMode(): void {
    this.isRegistering = !this.isRegistering;
    this.error = '';
  }
}

<div class="login-container">
  <div class="login-card">
    <div class="login-header">
      <h1>StudySync</h1>
      <p class="tagline">UNC Class & Professor Ratings</p>
    </div>

    <div class="auth-toggle">
      <button
        type="button"
        [class.active]="!isRegistering"
        (click)="isRegistering = false; error = ''"
      >
        Sign In
      </button>
      <button
        type="button"
        [class.active]="isRegistering"
        (click)="isRegistering = true; error = ''"
      >
        Sign Up
      </button>
    </div>

    <form (ngSubmit)="onSubmit()" class="auth-form" #loginForm="ngForm">
      <div *ngIf="error" class="error-message">{{ error }}</div>

      <div class="form-group">
        <label for="email">UNC Email</label>
        <input
          type="email"
          id="email"
          name="email"
          [(ngModel)]="formData.email"
          placeholder="yourname@unc.edu"
          required
          [disabled]="loading"
        />
      </div>

      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          name="password"
          [(ngModel)]="formData.password"
          [placeholder]="isRegistering ? 'At least 8 characters with letters and numbers' : 'Enter your password'"
          required
          [disabled]="loading"
          [minlength]="isRegistering ? 8 : 0"
        />
      </div>

      <ng-container *ngIf="isRegistering">
        <div class="form-group">
          <label for="major">Major</label>
          <select
            id="major"
            name="major"
            [(ngModel)]="formData.major"
            required
            [disabled]="loading"
          >
            <option value="">Select your major</option>
            <option *ngFor="let major of majors" [value]="major">{{ major }}</option>
          </select>
        </div>

        <div class="form-group">
          <label for="gradYear">Graduation Year</label>
          <select
            id="gradYear"
            name="gradYear"
            [(ngModel)]="formData.gradYear"
            required
            [disabled]="loading"
          >
            <option *ngFor="let year of gradYears" [value]="year">{{ year }}</option>
          </select>
        </div>
      </ng-container>

      <button
        type="submit"
        class="submit-button"
        [disabled]="loading || !loginForm.valid"
      >
        {{ loading ? 'Loading...' : (isRegistering ? 'Create Account' : 'Sign In') }}
      </button>
    </form>

    <div class="login-footer">
      <p>
        {{ isRegistering ? 'Already have an account?' : "Don't have an account?" }}
        <button
          type="button"
          class="link-button"
          (click)="toggleMode()"
        >
          {{ isRegistering ? 'Sign In' : 'Sign Up' }}
        </button>
      </p>
    </div>
  </div>
</div>
